/**
 * Audit compliance footer for exported reports.
 *
 * Appends to CSV exports so auditors can verify the translation method,
 * framework, and primary-currency history for any report period.
 */

export type AuditFramework = 'IFRS' | 'US_GAAP' | 'IFRS_AND_GAAP';
export type FxTranslationMethod = 'closing-rate' | 'period-average' | 'historical-per-transaction';
export type ReportCurrencyMode = 'wallet' | 'primary' | 'secondary';

export interface AuditFooterParams {
  reportType: string;
  reportTitle: string;
  dateLabel: string;
  primaryCurrency: string;
  secondaryCurrency: string | null;
  currencyMode: ReportCurrencyMode;
  framework: AuditFramework;
  fxTranslationMethod: FxTranslationMethod;
  hasBoundary: boolean;
  primaryCurrencyHistory?: Array<{
    primary_currency: string;
    effective_from: string | null;
    effective_to: string | null;
  }>;
  totalFxGain?: number;
  totalFxLoss?: number;
}

const FRAMEWORK_LABEL: Record<AuditFramework, string> = {
  IFRS: 'IFRS (IAS 21)',
  US_GAAP: 'US GAAP (ASC 830)',
  IFRS_AND_GAAP: 'IFRS (IAS 21) + US GAAP (ASC 830)',
};

const TRANSLATION_LABEL: Record<FxTranslationMethod, string> = {
  'closing-rate': 'Closing rate (balance-sheet date)',
  'period-average': 'Period-average rate',
  'historical-per-transaction': 'Historical rate per transaction',
};

const STANDARD_REF: Record<AuditFramework, string> = {
  IFRS: 'IAS 21 "The Effects of Changes in Foreign Exchange Rates"',
  US_GAAP: 'ASC 830 "Foreign Currency Matters"',
  IFRS_AND_GAAP: 'IAS 21 / ASC 830 dual-reporting',
};

/**
 * Build an array of CSV rows that form the audit compliance footer.
 * Returns rows as string arrays ready to be appended to the CSV payload.
 */
export function buildAuditFooterRows(p: AuditFooterParams): string[][] {
  const rows: string[][] = [];

  rows.push([]);
  rows.push(['--- AUDIT COMPLIANCE NOTE ---']);
  rows.push(['Report', p.reportTitle]);
  rows.push(['Period', p.dateLabel]);
  rows.push(['Generated', new Date().toISOString()]);
  rows.push([]);

  rows.push(['Accounting Framework', FRAMEWORK_LABEL[p.framework] ?? p.framework]);
  rows.push(['Standard Reference', STANDARD_REF[p.framework] ?? '']);
  rows.push(['Primary Currency', p.primaryCurrency]);
  if (p.secondaryCurrency) {
    rows.push(['Secondary Currency', p.secondaryCurrency]);
    rows.push([
      'Translation Method',
      TRANSLATION_LABEL[p.fxTranslationMethod] ?? p.fxTranslationMethod,
    ]);
  }
  rows.push([
    'Report View',
    p.currencyMode === 'primary'
      ? `Primary (${p.primaryCurrency})`
      : p.currencyMode === 'secondary'
        ? `Secondary (${p.secondaryCurrency})`
        : 'Wallet (native)',
  ]);

  if (p.hasBoundary && p.primaryCurrencyHistory && p.primaryCurrencyHistory.length > 1) {
    rows.push([]);
    rows.push(['PRIMARY CURRENCY HISTORY', '']);
    rows.push(['Currency', 'Effective From', 'Effective To']);
    for (const era of p.primaryCurrencyHistory) {
      rows.push([
        era.primary_currency,
        era.effective_from ?? 'inception',
        era.effective_to ?? 'present',
      ]);
    }
    rows.push([
      'Note',
      'This report spans a primary-currency change boundary. Split view shows each era separately.',
    ]);
  }

  if (p.totalFxGain != null || p.totalFxLoss != null) {
    rows.push([]);
    rows.push(['FX GAIN / LOSS RECONCILIATION', '']);
    if (p.totalFxGain != null) rows.push(['Unrealized FX Gain', String(p.totalFxGain)]);
    if (p.totalFxLoss != null) rows.push(['Unrealized FX Loss', String(p.totalFxLoss)]);
    if (p.totalFxGain != null && p.totalFxLoss != null) {
      rows.push(['Net FX Delta', String(p.totalFxGain - p.totalFxLoss)]);
    }
  }

  rows.push([]);
  rows.push(['DISCLOSURE', '']);
  rows.push([
    'Translation basis',
    `Monetary items remeasured at closing rate per ${STANDARD_REF[p.framework] ?? p.framework}.`,
  ]);
  rows.push(['Non-monetary items', 'Carried at historical cost. Not remeasured.']);
  rows.push([
    'Pending rates',
    'Lines with unresolved exchange rates are excluded from totals. Resolve via Admin > Exchange Rates.',
  ]);
  rows.push([]);
  rows.push([
    'Generated by Orange Way Books. Encrypted client-side; server never sees plaintext amounts.',
  ]);

  return rows;
}

/**
 * Serialize audit footer rows to a CSV string fragment (no BOM — appended to existing CSV).
 */
export function auditFooterCsv(params: AuditFooterParams): string {
  const rows = buildAuditFooterRows(params);
  const escape = (val: string): string => {
    if (val.includes(',') || val.includes('"') || val.includes('\n')) {
      return `"${val.replace(/"/g, '""')}"`;
    }
    return val;
  };
  return rows.map((row) => row.map(escape).join(',')).join('\n');
}
