-- DL-1348: Atomic org-creation RPC (SECURITY DEFINER)
--
-- Replaces the four client-side inserts in OnboardingWizard.handleFinish
-- (organizations, org_members, org_settings x2) with a single atomic RPC.
-- The client calls this function, receives the server-generated org_id, and
-- continues with the fire-and-forget chart-of-accounts seed.
--
-- DROP + CREATE (not CREATE OR REPLACE) per DBA ruling: the new function
-- changes the shape (SECURITY DEFINER, pinned search_path, hardened grants),
-- and CREATE OR REPLACE cannot alter return type or cleanly reset grants.
-- The IF EXISTS guard makes this migration safe to re-run.

-- Belt-and-suspenders drop of any stale prototype applied manually.
DROP FUNCTION IF EXISTS public.create_org_for_current_user(
  text, integer,
  text, text, text, text, text, text, text, text, text, integer,
  text, text, integer, text, text
);

CREATE FUNCTION public.create_org_for_current_user(
  -- Organization row
  p_org_name                        text,          -- encrypted ciphertext
  p_key_version                     integer,       -- e.g. 2 for L2

  -- org_settings columns (all ciphertext; server never sees plaintext)
  p_settings_primary_currency       text    DEFAULT NULL,
  p_settings_secondary_currency     text    DEFAULT NULL,
  p_settings_bitcoin_display        text    DEFAULT NULL,
  p_settings_fiscal_year_type       text    DEFAULT NULL,
  p_settings_encrypted_fiscal_month text    DEFAULT NULL,
  p_settings_date_format            text    DEFAULT NULL,
  p_settings_time_format            text    DEFAULT NULL,
  p_settings_number_format          text    DEFAULT NULL,
  p_settings_timezone               text    DEFAULT NULL,
  p_settings_key_version            integer DEFAULT NULL,

  -- Vault data (optional; set when vault is initialised during onboarding)
  p_vault_verifier                  text    DEFAULT NULL,
  p_vault_salt                      text    DEFAULT NULL,
  p_vault_key_version               integer DEFAULT NULL,
  p_enc_mek_ciphertext              text    DEFAULT NULL,
  p_recovery_ciphertext             text    DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
-- Pin search_path to prevent privilege-escalation via schema injection.
SET search_path = public, pg_temp
AS $$
DECLARE
  v_caller  uuid := auth.uid();
  v_org_id  uuid;
BEGIN
  -- Reject unauthenticated callers (belt-and-suspenders; the GRANT below
  -- already blocks anon/public, but an explicit check surfaces a clear error).
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'not authenticated'
      USING ERRCODE = '28000';
  END IF;

  -- 1. Create the organization.
  --    org_id is generated by the INSERT DEFAULT (gen_random_uuid()) so the
  --    caller never supplies or controls it.
  --    Two triggers fire automatically on this INSERT:
  --      auto_insert_org_owner:
  --        inserts the OWNER org_members row using auth.uid() (not a param).
  --      auto_provision_billing_for_new_org:
  --        provisions billing_account + subscription for the new org.
  INSERT INTO public.organizations (name, key_version)
  VALUES (p_org_name, p_key_version)
  RETURNING id INTO v_org_id;

  -- 2. Insert org_settings (all values are ciphertext from the client).
  --    NOT NULL columns with table defaults (fx_translation_method,
  --    accounting_framework, dek_key_version, invoice_next_number,
  --    invoice_prefix) are intentionally omitted here; their defaults apply.
  --    fiscal_start_month is always NULL for L2 orgs (the value lives in
  --    encrypted_fiscal_month).
  INSERT INTO public.org_settings (
    org_id,
    primary_currency,
    secondary_currency,
    bitcoin_display,
    fiscal_year_type,
    encrypted_fiscal_month,
    fiscal_start_month,
    date_format,
    time_format,
    number_format,
    timezone,
    key_version,
    vault_verifier,
    vault_salt,
    vault_key_version,
    enc_mek_ciphertext,
    recovery_ciphertext
  ) VALUES (
    v_org_id,
    p_settings_primary_currency,
    p_settings_secondary_currency,
    p_settings_bitcoin_display,
    p_settings_fiscal_year_type,
    p_settings_encrypted_fiscal_month,
    NULL,
    p_settings_date_format,
    p_settings_time_format,
    p_settings_number_format,
    p_settings_timezone,
    p_settings_key_version,
    p_vault_verifier,
    p_vault_salt,
    p_vault_key_version,
    p_enc_mek_ciphertext,
    p_recovery_ciphertext
  );

  RETURN v_org_id;
END;
$$;

-- Harden grants. Default Postgres behaviour grants EXECUTE to PUBLIC on new
-- functions; explicitly revoke that and grant only to authenticated callers.
REVOKE EXECUTE ON FUNCTION public.create_org_for_current_user(
  text, integer,
  text, text, text, text, text, text, text, text, text, integer,
  text, text, integer, text, text
) FROM public;

REVOKE EXECUTE ON FUNCTION public.create_org_for_current_user(
  text, integer,
  text, text, text, text, text, text, text, text, text, integer,
  text, text, integer, text, text
) FROM anon;

GRANT EXECUTE ON FUNCTION public.create_org_for_current_user(
  text, integer,
  text, text, text, text, text, text, text, text, text, integer,
  text, text, integer, text, text
) TO authenticated;

NOTIFY pgrst, 'reload schema';
