-- SUPERSEDED. This file is intentionally empty of DDL. Do not add any.
--
-- The split-transaction journal-entry linkage columns on public.transactions
-- and public.journal_entry_lines are created by
-- 20260512000001_split_tx_je_linkage.sql, which is the earlier of the two
-- copies and is the canonical definition. This file was a second copy of the
-- same change (OW-T0197); its DDL was byte identical, additive, and
-- idempotent (ADD COLUMN IF NOT EXISTS), so nothing was ever applied twice
-- and no schema outcome depended on which copy ran.
--
-- It is kept as an empty marker rather than deleted only because removing a
-- path is not available to the database steward's tooling. It executes
-- nothing and records nothing, so it is safe to apply and safe to skip. Any
-- seat with a working copy of this repository should delete it outright.
